default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: vgw12345

development:
  <<: *default
  database: depot_development







test:
  <<: *default
  database: depot_test

production:
  <<: *default
  database: depot_production
  username: depot
  password: <%= ENV['DEPOT_DATABASE_PASSWORD'] %>
